version: 2
updates:
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: cargo
    directory: /backend
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
