import books from '../books.json' with { type: 'json' }
import fs from 'fs'

let output = `// THIS FILE IS GENERATED BY CODE. DO NOT EDIT.
// THIS FILE CAN BE EDITED BY EDITING 'books.json' and running 'pnpm books'\n`

for (const [key, value] of Object.entries(books)) {
  output += `\nexport type ${key} = ${JSON.stringify(value, undefined, 4)}\n`
}

fs.writeFileSync('app/books_data.ts', output)
