import books from '../books.json' with { type: 'json' }
import fs from 'fs'
import stringify from 'json-stringify-pretty-compact'

let output = `// THIS FILE IS GENERATED BY CODE. DO NOT EDIT.
// THIS FILE CAN BE EDITED BY EDITING 'books.json' and running 'pnpm books'\n`

for (const [key, value] of Object.entries(books)) {
  output += `\nexport type ${key} = ${stringify(value, { indent: 2, maxLength: 100 })}\n`
}

fs.writeFileSync('app/books_data.ts', output)
