import books from '../books.json' with { type: 'json' }
import fs from 'fs'
import stringify from 'json-stringify-pretty-compact'

const booksDataStr = stringify(books, { indent: 2, maxLength: 100 })

const output = `// THIS FILE IS GENERATED BY CODE. DO NOT EDIT.
// THIS FILE CAN BE EDITED BY EDITING 'books.json' and running 'pnpm books'

export type BooksData = ${booksDataStr}

export const booksData: BooksData = ${booksDataStr}
`

fs.writeFileSync('app/books_data.ts', output)
