display_name = "EANV"

[book_aliases.books]
JHN = ["Test"]

[search]
languages = ["eng"]
ignored_words = [
    "a", "A",
    "an", "An", "AN",
    "the", "The", "THE",
    "of", "Of", "OF",
    "and", "And", "AND",
]

[[footnotes.Allah]]
books = "OT"
footnote = "\\f +\\ft This word shows up as \\nd Lord\\nd* in most English translation\\f*"
