display_name = "EANV"

[book_aliases.books]
JHN = ["Test"]

[search]
languages = ["eng"]
ignored_words = [
    "a", "A",
    "an", "An", "AN",
    "the", "The", "THE",
    "of", "Of", "OF",
    "and", "And", "AND",
]

[[footnotes.Allah]]
bible_ranges = [["Genesis 1", "Revelation 22"]]
footnote = "\\f +\\ft This word shows up as \\nd Lord\\nd* in most English translations.\\f*"

[[footnotes.Darkness]]
bible_ranges = ["Genesis 1:3"]
footnote = "\\f +\\ft In the Greek, this is Windex.\\f*"
