# fly.toml app configuration file generated for bible-web-framework on 2026-04-10T01:05:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bible-web-framework'
primary_region = 'ord'

[env]
DEFAULT_BIBLE = 'eanv'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "5s"
timeout = "60s"
path = "/v1/bibles"

[deploy]
strategy = "bluegreen"

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
