name: Rust Lint
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: 3
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: Swatinem/rust-cache@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install frontend dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint
